# Generated by Django 2.2.5 on 2019-09-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0002_csvdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorgroup',
            name='year_group',
            field=models.IntegerField(null=True),
        ),
    ]
