# Generated by Django 2.2.5 on 2020-02-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0002_teachingstrategy_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalSpatialBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DataDashboard.LocalStudent')),
            ],
        ),
    ]
