# Generated by Django 2.2.5 on 2020-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0003_verbalspatialbias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbalspatialbias',
            name='student',
        ),
        migrations.AddField(
            model_name='verbalspatialbias',
            name='student_id',
            field=models.IntegerField(default='0', unique=True),
            preserve_default=False,
        ),
    ]
