# Generated by Django 2.2.5 on 2019-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0003_auto_20190923_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='eal_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sen_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
