# Generated by Django 2.2.5 on 2019-09-24 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0004_auto_20190923_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summativedata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='summativedefinition',
            name='increment',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='summativedefinition',
            name='max_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summativedefinition',
            name='min_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summativedefinition',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataDashboard.SummativeScheme'),
        ),
    ]
