# Generated by Django 2.2.5 on 2020-02-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0004_auto_20200220_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMSSummativeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_id', models.IntegerField(blank=True, null=True)),
                ('aspect_name', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('result_value', models.FloatField(blank=True, null=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('aspect_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sims].[DataDashboard_summativedata',
                'managed': False,
            },
        ),
    ]
