# Generated by Django 2.2.5 on 2020-02-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0005_simssummativedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAT4GradeProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=3)),
                ('probability', models.FloatField()),
                ('cumulative_probability', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataDashboard.LocalStudent')),
            ],
            options={
                'unique_together': {('student', 'subject', 'qualification', 'grade')},
            },
        ),
    ]
