# Generated by Django 2.2.5 on 2019-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0005_auto_20190924_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
