# Generated by Django 2.2.5 on 2019-10-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0007_auto_20190927_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=2)),
                ('integer_year', models.IntegerField(null=True)),
                ('heads_of_year', models.ManyToManyField(blank=True, to='DataDashboard.Teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorgroup',
            name='year_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataDashboard.YearGroup'),
        ),
    ]
