# Generated by Django 2.2.5 on 2020-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0008_tutorialcategory_tutorialpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpage',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
