# Generated by Django 2.2.5 on 2019-10-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0008_auto_20191015_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeargroup',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
