# Generated by Django 2.2.5 on 2020-04-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0009_tutorialpage_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialpage',
            name='video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
