# Generated by Django 2.2.5 on 2020-04-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0010_auto_20200430_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpage',
            name='video_end',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='tutorialpage',
            name='video_start',
            field=models.IntegerField(default=0),
        ),
    ]
