# Generated by Django 2.2.5 on 2019-10-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0010_auto_20191015_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='summativedata',
            name='raw_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
