# Generated by Django 2.2.5 on 2020-05-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0012_coversheet_subject_term_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coversheet',
            name='yeargroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DataDashboard.YearGroup'),
        ),
    ]
