# Generated by Django 2.2.5 on 2019-10-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0012_auto_20191015_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinggroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataDashboard.Department'),
        ),
        migrations.AddField(
            model_name='teachinggroup',
            name='yeargroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataDashboard.YearGroup'),
        ),
        migrations.AlterField(
            model_name='yeargroup',
            name='year',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
