# Generated by Django 2.2.5 on 2020-05-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0013_coversheet_yeargroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coversheet',
            unique_together={('topic', 'term', 'yeargroup')},
        ),
    ]
