# Generated by Django 2.2.5 on 2019-12-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0014_simsstudent_simssubject_simsteachinggroup_teachingstrategy_teachingstrategycomment_teachingstrategyr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMSTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('salutation', models.CharField(max_length=20, null=True)),
                ('staff_code', models.CharField(max_length=5, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(max_length=5)),
                ('UPN', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'sims].[DataDashboard_teacher',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
    ]
