# Generated by Django 2.2.5 on 2019-11-04 02:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0014_department_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today)),
                ('name_on_marksheet', models.CharField(blank=True, max_length=100, null=True)),
                ('AB_value', models.IntegerField(null=True)),
                ('OB_value', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DataDashboard.Department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataDashboard.LocalStudent')),
            ],
        ),
    ]
