# Generated by Django 2.2.5 on 2019-12-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0015_auto_20191205_0830'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='simsteacher',
            table='sims].[DataDashboard_teachers',
        ),
    ]
