# Generated by Django 2.2.5 on 2019-11-04 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0015_abob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abob',
            name='department',
        ),
        migrations.RemoveField(
            model_name='abob',
            name='name_on_marksheet',
        ),
        migrations.CreateModel(
            name='MarksheetDeptAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sims_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataDashboard.Department')),
            ],
        ),
        migrations.AddField(
            model_name='abob',
            name='marksheet_alias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataDashboard.MarksheetDeptAlias'),
        ),
    ]
