# Generated by Django 2.2.5 on 2019-12-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0016_auto_20191205_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simsteacher',
            options={'managed': False, 'ordering': ['staff_code']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['staff_code']},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='UPN',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='house',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salutation',
        ),
        migrations.AddField(
            model_name='teacher',
            name='firstname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lastname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title_des',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='staff_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
