# Generated by Django 2.2.5 on 2019-12-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0016_auto_20191104_1034'),
        ('DataDashboard', '0017_auto_20191205_0848'),
    ]

    operations = [
    ]
