# Generated by Django 2.2.5 on 2019-12-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0018_merge_20191206_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingStrategyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marksheetdeptalias',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='teachinggroup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teachinggroup',
            name='yeargroup',
        ),
        migrations.AddField(
            model_name='teachingstrategycomment',
            name='downvote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingstrategycomment',
            name='upvote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yeargroup',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ABOB',
        ),
        migrations.DeleteModel(
            name='MarksheetDeptAlias',
        ),
        migrations.AddField(
            model_name='teachingstrategy',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataDashboard.TeachingStrategyCategory'),
        ),
    ]
