# Generated by Django 2.2.5 on 2019-12-06 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0019_auto_20191206_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstrategycomment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
