# Generated by Django 2.2.5 on 2019-12-06 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0020_teachingstrategycomment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstrategycomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='DataDashboard.Teacher'),
        ),
    ]
