# Generated by Django 2.2.5 on 2019-12-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0022_auto_20191206_0403'),
        ('DataDashboard', '0018_merge_20191208_2359'),
    ]

    operations = [
    ]
