# Generated by Django 2.2.5 on 2019-12-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0022_auto_20191206_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingstrategycomment',
            name='vote',
            field=models.IntegerField(blank=True, choices=[(1, 'Upvote'), (-1, 'Downvote')], null=True),
        ),
    ]
