# Generated by Django 2.2.5 on 2019-12-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0023_auto_20191209_0153'),
        ('DataDashboard', '0023_merge_20191209_0030'),
    ]

    operations = [
    ]
