# Generated by Django 2.2.5 on 2019-12-09 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataDashboard', '0024_auto_20191209_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalStudent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('preferred_forename', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1000)),
                ('parent_email', models.EmailField(max_length=1000)),
                ('parent_salutation', models.CharField(max_length=1000)),
                ('student_email', models.EmailField(max_length=1000)),
                ('house_id', models.CharField(max_length=1000)),
                ('tutor_group_id', models.CharField(max_length=1000)),
                ('full_name', models.CharField(max_length=1000)),
                ('EAL_status', models.CharField(max_length=1000)),
                ('SEN_status', models.CharField(max_length=1000)),
                ('exam_candidate_number', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'sims].[DataDashboard_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalTeachingGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teaching_group', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'sims].[DataDashboard_teachinggroup',
                'managed': False,
            },
        ),
    ]
